# Generated by Django 3.0.4 on 2020-06-25 00:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hwdPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictNum', models.PositiveSmallIntegerField()),
                ('canvasData', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=800), blank=True, size=None)),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
